#:import get_color_from_hex kivy.utils.get_color_from_hex

BoxLayout:
	orientation: "vertical"
	
	canvas.before:
		Color:
			rgba: get_color_from_hex('#666666')
		Rectangle:
			pos: self.pos
			size: self.size
	
	Label:
		id: product_name
		text: "PRODUCT_NAME"
		font_size: 20
	
	Label:
		id: product_price
		text: "PRODUCT_PRICE"
		font_size: 10
		
	Button:
		id: buy_button
		name: ""
		text: "Comprar"
		size_hint: 1, None